version: "3.3"

services:
  fetcher:
    build: fetcher
    environment:
      - CONFIG=/data/config.yaml
    volumes:
      - ./data:/data
    command: bash -c 'ruby ./fetcher.rb'

  expire:
    build: expire
    environment:
      - CONFIG=/data/config.yaml
      - SERVER=http://nginx
      - BYPASS=bypass
    volumes:
      - ./data:/data
    command: sh -c 'ruby ./get_tiles.rb'
    depends_on:
      merge_proxy:
        condition: service_healthy
      nginx:
        condition: service_started
