version: "3.3"

services:
  vt_merge_proxy_fetcher:
    build: vt_merge_proxy_fetcher
    volumes:
      - ./data:/data
    command: bash -c 'ruby ./update.rb /data/config.yaml'

  expire:
    build: expire
    volumes:
      - ./data:/data
    environment:
      - HOST=nginx
    command: sh -c 'ruby ./get_tiles.rb /data/config.yaml http://nginx/ bypass'
