version: "3.3"

services:
  merge_proxy:
    build:
      context: merge_proxy
    environment:
      - CONFIG=/data/config.yaml
    volumes:
      - ./data:/data
#    restart: unless-stopped

  nginx:
    image: nginx
    volumes:
      - cache:/cache
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ./nginx.htpasswd:/etc/nginx/.htpasswd
    ports:
      - ${NGINX_PORT:-8080}:80
    depends_on:
      - merge_proxy
#    restart: unless-stopped

volumes:
    cache:
