version: "3.3"

services:
  vt_merge_proxy_fetcher:
    build: vt_merge_proxy_fetcher
    volumes:
      - ./data:/data
    command: bash -c './update.sh "${DATA_API_URL}" /data'

  expire:
    build: expire
    command: bash -c 'python ./get_tiles.py "http://nginx/data/${DATA_SET}/{z}/{x}/{y}.pbf?key=${TILES_API_KEY}" bypass $MIN_X $MIN_Y $MAX_X $MAX_Y'
