version: "3.3"

services:
  fetcher:
    build: fetcher
    volumes:
      - ./data:/data
    command: bash -c 'ruby ./update.rb /data/config.yaml'

  expire:
    build: expire
    volumes:
      - ./data:/data
    command: sh -c 'ruby ./get_tiles.rb /data/config.yaml http://nginx bypass'
