on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
          cache-dependency-path: |
            merge_proxy/requirements.txt
            merge_proxy/requirements-dev.txt

      - name: Install proj
        run: sudo apt-get update && sudo apt-get install -y proj-bin libproj-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r merge_proxy/requirements.txt -r merge_proxy/requirements-dev.txt

      - uses: psf/black@stable
        with:
          version: "~= 24.0"

      - name: Run flake8
        run: (cd merge_proxy && python -m flake8 merge_proxy/)

      - name: Run mypy
        run: (cd merge_proxy && python -m mypy merge_proxy/)

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.13]
        # include:
        #   - os: macos-latest
        #     python-version: 3.13
        #   - os: windows-latest
        #     python-version: 3.13
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: |
          merge_proxy/requirements.txt
          merge_proxy/requirements-test.txt

    - name: System information
      run: python .github/workflows/system_info.py

    - name: Install proj
      run: sudo apt-get update && sudo apt-get install -y proj-bin libproj-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r merge_proxy/requirements.txt -r merge_proxy/requirements-test.txt

    - name: Test with pytest
      working-directory: merge_proxy
      run: |
        python -m pytest --cov=package_name --cov-report term --cov-report xml --cov-config .coveragerc --junitxml=testresults.xml

  docker:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.ref == 'refs/heads/master'

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Docker Build and Push
        uses: cartoway/docker-compose-build-push-action@main
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
